version: '3.7'

services:
  web:
    image: hyeogju_web_image
    networks:
      - hyeogju_net
    ports:
      - "80:80"
    links:
      - was:hyeogju
    restart: always
    entrypoint:
      - "nginx"
      - "-g"
      - "daemon off;"
    depends_on:
      - was
  was:
    image: hyeogju_app_image
    networks:
      - hyeogju_net
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - db:hyeogju_db
    entrypoint:
      - "java"
      - "-jar"
      - "-Duser.timezone=Asia/Seoul"
      - "/app.jar"
    depends_on:
      - db
  db:
    image: mariadb
    networks:
      - hyeogju_net
    restart: always
    environment:
      - MARIADB_DATABASE=hyeogju_db
      - MARIADB_USER=fada2020
      - MARIADB_PASSWORD=guswn0731
      - MARIADB_ROOT_PASSWORD=guswn0731
    #volumes:
    #  - /build/DB/mariadb:/var/lib/mariadb
    ports:
      - "3306:3306"

networks:
  hyeogju_net:


## docker network create mynet
## docker run --name mariadb -d -p 3306:3306 --restart=always -e MYSQL_ROOT_PASSWORD=guswn0731  -e MARIADB_DATABASE=hyeogju_db  -e MARIADB_USER=fada2020  -e MARIADB_PASSWORD=guswn0731 --network mynet mariadb:tag --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  

